### PR TITLE
return error for not found case makes checking existence fail

### LINKED ISSUE #91: Failed to create VM with controller
The controller keeps reporting 

```
E0430 07:29:52.704560       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:29:54.361228       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:29:55.860904       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:29:57.348960       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:29:58.802661       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:30:00.266265       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:30:02.001480       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:30:03.507305       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:30:05.266735       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:30:07.061822       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:30:10.370779       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:30:15.976063       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:30:26.813584       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:30:47.778407       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:31:29.341248       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
E0430 07:32:51.824460       1 controller.go:202] Failed to check if machine "liugya-master-k6dqx" exists: Virtual guest "liugya-master-k6dqx" does not found
```

### PR DESCRIPTION
**Pull request by xunpan**
Machine actuator API of `Exists` return `true` or `false` with no error for common check. It is error if other condition happens in API implementation.

Previously, I try to use not found case as an error. It is not convenient for this case and make API logic wrong

Fixes #91

### CODE REVIEW

File: pkg/cloud/ibmcloud/actuators/machine/actuator.go [hunk 1]
```diff
@@ -129,6 +129,10 @@ func (ic *IbmCloudClient) Create(ctx context.Context, cluster *clusterv1.Cluster
 		return err
 	}
 
+	if guest == nil {
+		return fmt.Errorf("Guest host does not found")
+	}
```
Comment (jichenjc) [inline pkg/cloud/ibmcloud/actuators/machine/actuator.go]: we are in guest create stage... so this info seems not very helpful 

you want to say that the create failed and we can't get the guest? @xunpan

Comment (xunpan) [reply pkg/cloud/ibmcloud/actuators/machine/actuator.go]: This is trying to keep logic correct.

`getGuest` will return `nil` with no error. I'm checking it and give a simple error message. If we do not make it, later `strconv.Itoa(*guest.Id)` will fail. Even we're creating machine at the time, I'm not sure if IBM Cloud or softlayer API failed to get `guest` in any cases. So, checking it for logic correct

Comment (jichenjc) [reply pkg/cloud/ibmcloud/actuators/machine/actuator.go]: ok, I submitted a PR to add more info about the log, thanks for the detailed info~
